services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/bloomberg?serverTimezone=UTC'
      SPRING_DATASOURCE_USERNAME: 'progresssoft'
      SPRING_DATASOURCE_PASSWORD: '123'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'bloomberg'
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: 'progresssoft'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: