spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bloomberg?serverTimezone=UTC
    username: progresssoft
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


